from app.services.auth_service import (
    login_required,
    role_required,
    admin_required,
    support_required,
    get_current_user,
    validate_email,
    validate_password,
)
from app.services.ticket_service import (
    generate_unique_ticket_number,
    create_ticket,
    add_ticket_message,
    add_support_reply,
    update_ticket_status,
    reopen_ticket,
    request_human_support,
    update_ticket_priority,
    update_ticket_category,
    update_ticket_team,
    add_internal_note,
    escalate_ticket,
    get_customer_stats,
    get_admin_stats,
    VALID_STATUS_TRANSITIONS,
)
from app.services.escalation_service import EscalationService
from app.services.notification_service import (
    create_notification,
    notify_support_staff,
    get_user_notifications,
    get_unread_count,
    mark_as_read,
    mark_all_as_read,
)
from app.services.rag.rag_service import RAGService

__all__ = [
    "login_required",
    "role_required",
    "admin_required",
    "support_required",
    "get_current_user",
    "validate_email",
    "validate_password",
    "generate_unique_ticket_number",
    "create_ticket",
    "add_ticket_message",
    "add_support_reply",
    "update_ticket_status",
    "reopen_ticket",
    "request_human_support",
    "update_ticket_priority",
    "update_ticket_category",
    "update_ticket_team",
    "add_internal_note",
    "escalate_ticket",
    "get_customer_stats",
    "get_admin_stats",
    "VALID_STATUS_TRANSITIONS",
    "EscalationService",
    "create_notification",
    "notify_support_staff",
    "get_user_notifications",
    "get_unread_count",
    "mark_as_read",
    "mark_all_as_read",
    "RAGService",
]
