from dataclasses import dataclass, field
from typing import Optional, List


@dataclass
class ChunkMetadata:
    """Metadata container for a document chunk."""
    document_id: int
    chunk_index: int
    document_title: str
    filename: str
    category: str
    page_number: Optional[int] = None


@dataclass
class RetrievedChunk:
    """A retrieved knowledge chunk with its similarity score."""
    chunk_id: int
    document_id: int
    chunk_index: int
    content: str
    document_title: str
    filename: str
    category: str
    similarity_score: float
    page_number: Optional[int] = None

    def to_dict(self) -> dict:
        return {
            "chunk_id": self.chunk_id,
            "document_id": self.document_id,
            "chunk_index": self.chunk_index,
            "content": self.content,
            "document_title": self.document_title,
            "filename": self.filename,
            "category": self.category,
            "similarity_score": round(self.similarity_score, 2),
            "similarity_percent": int(round(self.similarity_score * 100)),
            "page_number": self.page_number,
        }


@dataclass
class RAGSourceResult:
    """Source reference citation for a grounded resolution."""
    document_id: int
    chunk_id: int
    source_title: str
    filename: str
    similarity_score: float
    excerpt: str
    page_number: Optional[int] = None

    def to_dict(self) -> dict:
        return {
            "document_id": self.document_id,
            "chunk_id": self.chunk_id,
            "source_title": self.source_title,
            "filename": self.filename,
            "page_number": self.page_number,
            "similarity_score": round(self.similarity_score, 2),
            "similarity_percent": int(round(self.similarity_score * 100)),
            "excerpt": self.excerpt,
        }


@dataclass
class RAGResolutionResult:
    """Structured resolution response generated by the RAG pipeline."""
    answer: str
    confidence: float
    needs_escalation: bool
    reason: str
    sources: List[RAGSourceResult] = field(default_factory=list)
    status: str = "COMPLETED"
    model_name: Optional[str] = None
    provider: Optional[str] = None
    retrieval_count: int = 0

    def validate(self) -> tuple[bool, str]:
        """Validate structure and confidence bounds."""
        if not self.answer or not self.answer.strip():
            return False, "Resolution answer cannot be empty."

        if self.confidence is None or not isinstance(self.confidence, (int, float)):
            return False, "Confidence must be a numeric score between 0.0 and 1.0."

        if not (0.0 <= float(self.confidence) <= 1.0):
            return False, f"Confidence {self.confidence} is out of bounds (0.0 to 1.0)."

        return True, ""

    def to_dict(self) -> dict:
        return {
            "answer": self.answer,
            "confidence": round(float(self.confidence), 2),
            "confidence_percent": int(round(float(self.confidence) * 100)),
            "needs_escalation": self.needs_escalation,
            "reason": self.reason,
            "status": self.status,
            "model_name": self.model_name,
            "provider": self.provider,
            "retrieval_count": self.retrieval_count,
            "sources": [s.to_dict() for s in self.sources],
        }
